I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script call
    call alex_a_home
  File "game/script.rpy", line 40, in script call
    call alex_a_home
ScriptError: could not find label 'alex_a_home'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script call
    call alex_a_home
  File "C:\Users\Anton\Renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 40, in script call
    call alex_a_home
  File "C:\Users\Anton\Renpy\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'alex_a_home'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
2024 1.0
Sat Dec 30 23:52:01 2023
